url:
  localhost: https://app.ilovegrowth.cn
logging:
    level:
        tk.mybatis: DEBUG
        com.igrowth.app: DEBUG
spring:
    http:
        multipart:
            enabled: true
            max-file-size: 50MB #(这里是限制的文件大小)
            max-request-size: 50MB #(这里是限制的文件大小)
    application:
        name: igrowth-app
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: NON_NULL
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        pool:
            max-active: 20
    datasource:
        name: test
        url: jdbc:mysql://123.57.157.44:3306/igrowth_app?useUnicode=true&characterEncoding=UTF8
        username: feichina
        password: xlgl1004
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.igrowth.app.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8799

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
        # docker 部署开启
        prefer-ip-address: true
        ip-address: 127.0.0.1
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            #defaultZone: http://center:8761/eureka/
swagger:
    basepackage: com.igrowth.app
    service:
        name: igrowth-app
        description: 爱成长app接口
        developer: 大飞


auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
    pub-key:
      path: jwt/pub.key
  client:
    id: igrowth-app
    secret: 123456
    token-header: client-token
    pub-key:
      path: client/pub.key
  
jwt:
  token-header: Authorization
  expire: 604800 #7天
  pri-key:
    path: jwt/pri.key
  pub-key:
    path: jwt/pub.key
